# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{i18n_sync}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcos Piccinini"]
  s.date = %q{2010-07-16}
  s.default_executable = %q{i18s}
  s.description = %q{Gem to sync all locale yml/rb files based on a "master" one.}
  s.email = %q{x@nofxx.com}
  s.executables = ["i18s"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/i18s",
     "i18n_sync.gemspec",
     "lib/i18n_sync.rb",
     "spec/fixtures/en.yml",
     "spec/fixtures/named.en.yml",
     "spec/fixtures/named.pt.yml",
     "spec/fixtures/order.en.yml",
     "spec/fixtures/order.pt.yml",
     "spec/fixtures/pt.yml",
     "spec/i18n_sync_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/nofxx/i18n_sync}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Syncs all locale yml/rb files based on a "master" one.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/i18n_sync_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

